trigger:
- main

pool: 
  name: Windows Agent

variables: 
  - template: variables.yml


stages:

- stage: ProductOrgQA
  displayName: Publish product to QA Organization
  jobs: 
  - deployment: PublishProduct
    workspace:
      clean: all
    displayName: Publishing product of QA
    environment: $(environmentValue)
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/publishing-product.yml